Zype/ViewController/VideoDetailViewController.m

- Player was showing green screen when navigating between monetized and free video

CORE 1774 - Green screen UI bug on autoplay navigation

---

Zype/ViewController/VideoDetailViewController.m
Zype/Views/PlayerControlsOverlay.m

**Updates**
- Added logic to hide and disable buttons for autoplay when setting is turned off in user preferences
- Update to allow scrubbing to last second

Core 1784 - Update player controls when autoplay turned off

---

Zype/AppDelegate.m
Zype/Controllers/BaseTVLayoutController.m
Zype/Utilities/ZypeCommon.h
Zype/Views/MediaItemCollectionCell.m
Zype/Views/MediaItemCollectionCell.xib
Zype/Views/PagerSectionCell.m
Zype/Views/PagerSectionCell.xib

Display playlist and video titles underneath each thumbnail image

Display playlist and video titles underneath each thumbnail image on iOS

---

Zype/Managers/ACActionSheetManager.m
Zype/ViewController/VideoDetailViewController.m

Fixed logical issue in the code - https://zypeinc.atlassian.net/browse/APPS-730

Fix for APPS-730 - iOS - Video download action brings plan selection view

---

Zype/Base.lproj/Main.storyboard
Zype/Utilities/HtmlTemplates/VideoSummary.html
Zype/Utilities/HtmlTemplates/VideoSummaryLight.html
Zype/Utilities/UIUtil.m
Zype/ViewController/HomeViewController.m
Zype/ViewController/LatestViewController.m
Zype/ViewController/MediaPlaybackBaseViewController.h
Zype/ViewController/MoreViewController.m
Zype/ViewController/PrivacyViewController.h
Zype/ViewController/PrivacyViewController.m
Zype/ViewController/SettingsDetailViewController.h
Zype/ViewController/SettingsDetailViewController.m
Zype/ViewController/SettingsViewController.h
Zype/ViewController/SettingsViewController.m
Zype/ViewController/SubsciptionViewController.m
Zype/ViewController/VideoDetailViewController.h
Zype/ViewController/VideoDetailViewController.m
Zype/ViewController/VideosViewController.m

JIRA - https://zypeinc.atlassian.net/browse/APPS-745
All the details related to changes, UI screenshots etc.. are provides as comments to APPS-745.

UIWebView replacement by WkWebView

---

Podfile
Zype.xcodeproj/project.pbxproj
Zype/AppDelegate.m
Zype/Managers/SegmentAnalyticsManager.swift
Zype/Utilities/ZypeCommon.h
Zype/ViewController/VideoDetailViewController.m

Details here - https://zypeinc.atlassian.net/browse/APPS-767

Segment Analytics Feature

---

Zype/Utilities/HtmlTemplates/VideoSummary.html
Zype/Utilities/HtmlTemplates/VideoSummaryLight.html
Zype/ViewController/VideoDetailViewController.m

JIRA - https://zypeinc.atlassian.net/browse/APPS-968

Font size fixes for video summary with episodes presence

---

Zype/Controllers/RESTServiceController.m

There was improper handling of failure scenario's for two requests getTokenInfo AND saveConsumerIdWithToken.
Fixed both the cases.

Fixed App crashes when used in Airplane mode (no WiFi connection)

---

Zype/Utilities/UIUtil.m
Zype/Utilities/ZypeCommon.h
Zype/ViewController/VideoDetailViewController.m

**Ticket** - https://zypeinc.atlassian.net/browse/APPS-1227

Create Feature Flag for "kShowEpisodeNumbers"

---

Zype/Base.lproj/Main.storyboard
Zype/Categories/UIView+UIView_CustomizeTheme.m
Zype/ViewController/ForgotPasswordViewController.m
Zype/ViewController/RegisterViewController.m
Zype/ViewController/SignInViewController.m
Zype/ViewController/WatcherSignInViewController.m
Zype/ViewController/WatcherSignUpViewController.m

comitted required changes

---

Zype/Controllers/BaseTableController.m
Zype/Info.plist
Zype/Views/PlaylistTableViewCell.xib

…llery View
All changes related to APPS-1217 have been merged.
1. Thumbnail size are changed
2. Fonts are added (NOTE: need to install the fonts in mac if running from xcode)

Implementation of the non-gallery view thumbnail sizing adjustment

---

Zype/Managers/SegmentAnalyticsManager.swift
Zype/ViewController/VideoDetailViewController.m

Merged new segment event reporting from ZPS-43 and fixed Video Content Completed and Video Playback Completed issue.
As discussed here https://zypeinc.atlassian.net/browse/APPS-1413?focusedCommentId=31184 we need to support both events on playback complete.

APPS-1413 Support for new Segment event reporting

---

Zype/ViewController/MoreViewController.m

JIRA https://zypeinc.atlassian.net/browse/APPS-1863

Fixed App Monetization Plans option appearing on AVOD app

---

Zype/Controllers/RESTServiceController.h
Zype/Controllers/RESTServiceController.m
Zype/Managers/ACSPersistenceManager.m
Zype/Utilities/ACSPredicates.m
Zype/Utilities/ZypeCommon.h
Zype/ViewController/DownloadsViewController.m

Video Status on Playlists Update

---

Zype/Utilities/ZypeCommon.h
Zype/ViewController/MoreViewController.m

JIRA - https://zypeinc.atlassian.net/browse/APPS-472

Sign In button hidden if SVOD, TVOD, Registration are disabled

---

Zype.xcodeproj/project.pbxproj
Zype/Base.lproj/Main.storyboard
Zype/Controllers/BaseCollectionController.m
Zype/Controllers/BaseTVLayoutController.m
Zype/Managers/ACActionSheetManager.h
Zype/Managers/ACActionSheetManager.m
Zype/Utilities/HtmlTemplates/VideoSummaryLightTablets.html
Zype/Utilities/HtmlTemplates/VideoSummaryTablets.html
Zype/ViewController/TabBarViewController.m
Zype/ViewController/UserPreferencesViewController.m
Zype/ViewController/VideoDetailViewController.m
Zype/ViewController/VideosViewController.m
Zype/Views/ACSEpisodeCollectionViewCell.m
Zype/Views/OptionTableViewCell.m
Zype/Views/OptionTableViewCell.xib
Zype/Views/PagerSectionCell.m
Zype/Views/VideoTableViewCell.m

JIRA https://zypeinc.atlassian.net/browse/APPS-1842

iPad Fixes 

---

Zype.xcodeproj/project.pbxproj
Zype.xcworkspace/xcshareddata/swiftpm/Package.resolved
Zype/AppDelegate.m
Zype/Info.plist
Zype/Utilities/ZypeCommon.h

APPS-1415: Integrated latest Facebook SDK into the template

Template iOS – Facebook SDK Implementation

---

.gitignore
Podfile
Podfile.lock

https://zypeinc.atlassian.net/browse/APPS-1938

Upgrade iOS OneSignal SDK to Minimum Version 2.16.5

---

Zype/Managers/SegmentAnalyticsManager.swift

JIRA - https://zypeinc.atlassian.net/browse/APPS-1939

Fixed SegmentAnalyticsManager open interface objC requirements from latest XCode

---

Zype/ViewController/VideoDetailViewController.m

Fixed the pre-roll ads in live video

Fixed the pre-roll ads in live video
